Repository CentaurusInfra/regionless-storage-service, pull requests merged in 2022-08, with the labels that each got.

#43 Added concurrent mode to improve performance
  .github/workflows/main.yaml
  cmd/http/config.json
  cmd/http/main.go
  pkg/config/config.go
  pkg/consistent/chain/node.go
  pkg/piping/chain_piping_manager.go
  test/piping/chain_piping_manager_test.go
Labels: ready-for-review

#44 fix scripts for the concurrent replication
  scripts/si_def_2_region_large.json
  scripts/si_def_4_region_large.json
  scripts/test-lab.val.micro
  scripts/test_infra/create_test_instances.sh
Labels: ready-for-review

#47 add a script to dynamically select storage instance config files
  scripts/select_config.sh
  scripts/si_def.json
  scripts/si_def_1_region_2xlarge.json
  scripts/si_def_1_region_micro.json
  scripts/si_def_2_region_medium.json
  scripts/si_def_2_region_micro.json
  scripts/si_def_4_region_2xlarge.json
  scripts/si_def_4_region_medium.json
  scripts/si_def_4_region_micro.json
  scripts/test-lab.val.2xlarge
  scripts/test-lab.val.medium
Labels: ready-for-review

#48 Added region types to config
  cmd/http/config.json
  cmd/http/main.go
  pkg/config/config.go
  test/config/config_test.go
Labels: ready-for-review

#50 refactor: introduce tracer pkg for tracing setup and custom prob sampler code
  cmd/http/main.go
  pkg/tracer/tracer.go
Labels: ready-for-review, refactoring

#53 minor: get rid of unnecessary restful http server lock
  cmd/http/main.go
Labels: ready-for-review

#55 Added latency measurement for backend datastores
  pkg/network/latency/latency.go
  pkg/network/latency/measure.go
  pkg/network/latency/net.go
  pkg/network/latency/summary.go
  test/network/latency/measure_test.go
  test/network/latency/summary_test.go
Labels: ready_for_preliminary_review

#59 create storages once
  cmd/http/config.json
  cmd/http/main.go
  pkg/config/config.go
  pkg/consistent/chain/chain.go
  pkg/database/database.go
  pkg/database/redis.go
Labels: ready-for-review

#61 introduces dummy+latency store type suitable as simulator used in perf test
  cmd/http/config.json
  cmd/http/main.go
  pkg/config/config.go
  pkg/database/database.go
  pkg/database/dymmydb.go
  pkg/database/latencydb.go
Labels: ready-for-review

#62 bug fix: stale rev still updates
  pkg/index/key_index.go
  pkg/index/key_index_test.go
Labels: ready-for-review

#63 Changes to load nodes in local zones and remote nodes based on connection latencies
  .github/workflows/main.yaml
  cmd/http/config.json
  cmd/http/main.go
  pkg/config/config.go
  pkg/consistent/chain/chain.go
  pkg/constants/availability_zone.go
  pkg/constants/region.go
  pkg/constants/store.go
  pkg/database/database.go
  pkg/partition/consistent/hashing.go
  pkg/partition/consistent/rendezvous.go
  pkg/partition/consistent/ring.go
  pkg/piping/chain_piping_manager.go
  test/config/config_test.go
  test/consistent/chain/chain_test.go
  test/partition/consistent/hashing_test.go
  test/partition/consistent/rendezvous_test.go
  test/partition/consistent/ring_test.go
  test/piping/chain_piping_manager_test.go
Labels: ready-for-review
